sudo: required

env:
  global:
    - KEYFILE=".travis/travis-keyfile.json"
    - DOCKER_IMAGE_NAME="eu.gcr.io/metanic-1356/metanic/alpine-glibc:3.4"

services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_a96c7aa650c7_key -iv $encrypted_a96c7aa650c7_iv
  -in ${KEYFILE}.enc -out $KEYFILE -d

install:
- docker login -e email@not-used.com -u _json_key -p "$(cat $KEYFILE)" https://eu.gcr.io

script:
- docker build -t $DOCKER_IMAGE_NAME .

after_success:
  - test $TRAVIS_BRANCH = "master" && docker push $DOCKER_IMAGE_NAME
